authors/urls.py
from django.urls import path

from authors import views

app_name = 'authors'

urlpatterns = [
    # * Register
    path("register/", views.register_view, name='register'),
    path("register/create/", views.register_create, name='register_create'),
    # * Login & Logout
    path("login/", views.login_view, name='login'),
    path("login/create/", views.login_create, name='login_create'),
    path("login/logout_view/", views.logout_view, name='logout_view'),
    # * Dashboard
    path("dashboard/", views.dashboard, name='dashboard'),
    path(
        "dashboard/recipe/",
        views.dashboard_recipe_view,
        name='dashboard_recipe_view'
    ),
    path(
        "dashboard/recipe/create/",
        views.dashboard_recipe_create,
        name='dashboard_recipe_create'
    ),
    path(
        "dashboard/recipe/<int:id>/edit/",
        # views.DashboardRecipe.as_view(),
        views.dashboard_recipe_edit,
        name='dashboard_recipe_edit'
    ),
    path(
        "dashboard/recipe/delete/",
        views.dashboard_recipe_delete,
        name='dashboard_recipe_delete'
    ),
]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('recipes.urls')),
    path("authors/", include('authors.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/urls.py
from django.urls import path

from recipes import views

app_name = 'recipes'

urlpatterns = [
    path("", views.home, name='home'),
    path("recipes/search/", views.search, name='search'),
    path("recipes/category/<int:category_id>/", views.category, name='category'),
    path("recipes/<int:id>/", views.recipe, name='recipe')
]

recipes/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils.text import slugify

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=65)
    
    def __str__(self):
        return self.name

class Recipe(models.Model):
    title = models.CharField(max_length=65)
    description = models.CharField(max_length=165)
    slug = models.SlugField(unique=True)
    preparation_time = models.IntegerField()
    preparation_time_unit = models.CharField(max_length=65)
    servings = models.IntegerField()
    servings_unit = models.CharField(max_length=65)
    preparation_steps = models.TextField()
    preparation_steps_is_html = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(default=False)
    cover = models.ImageField(upload_to='recipes/cover/%Y/%m/%d/')
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("recipes:recipe", kwargs={"id": self.id})
    
    def save(self, *args, **kwargs):
        if not self.slug:
            slug = slugify(self.title)
            self.slug = slug
            
        return super().save(*args, **kwargs)
    
# EDIT
# title description slug
# preparation_time preparation_time_unit
# servings servings_unit
# preparation_step
# preparation_step_is_html
# created_at updated_at
# is_published
# cover
# category (Relação)
# Author (Relação)

authors/forms/RecipeForm.py
from collections import defaultdict

from django import forms
from django.core.exceptions import ValidationError

from recipes.models import Recipe
from utils.django_forms import add_attr


class RecipeForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        self._my_errors = defaultdict(list)
        
        add_attr(self.fields.get('preparation_steps'), 'parentClassName', 'col-md-12')
        add_attr(self.fields.get('cover'), 'parentClassName', 'col-md-12')
     
        add_attr(self.fields.get('preparation_steps'), 'class', 'form-control')
        add_attr(self.fields.get('cover'), 'class', 'form-control')
    
    preparation_time_unit = forms.CharField(
        required=True,
        widget=forms.Select(
            attrs={
            'class': 'form-control'
            },
            choices=(
                ('Minutos', 'Minutos'),
                ('Horas', 'Horas'),
            )
        ),
        label="Preparation Time Unit",
    )
    
    servings_unit = forms.CharField(
        required=True,
        widget=forms.Select(
            # attrs={
            # 'class': 'form-control'
            # },
            choices=(
                ('Porções', 'Porções'),
                ('Pedaços', 'Pedaços'),
                ('Pessoas', 'Pessoas'),
            )
        ),
        label="Servings Unit",
    )
    
    class Meta:
        model=Recipe
        fields= ('title', 'description', 'preparation_time', 'preparation_time_unit', 'servings', 'servings_unit', 'category', 'preparation_steps', 'cover')
        
    def clean(self, *args, **kwargs):
        super_clean = super().clean(*args, **kwargs)
        
        cleaned_data = self.cleaned_data
        title = cleaned_data.get('title')
        description = cleaned_data.get('description')
        
        if len(title or '') < 5:
            self._my_errors['title'].append('Must have at least 5 chars')
            
        if title == description:
            self._my_errors['title'].append('Title and description cannot be equal')
            self._my_errors['description'].append('Title and description cannot be equal')
            
        if self._my_errors:
            raise ValidationError(self._my_errors)
        
        return super_clean

recipes/views.py
from os import environ

from django.db.models import Q
from django.http import Http404, HttpResponse
from django.shortcuts import render

from recipes.models import Recipe
from utils.pagination import make_pagination

PER_PAGE = int(environ.get('PER_PAGE'))
QTY_PAGES = int(environ.get('QTY_PAGES'))

# Create your views here.
def home(request):
    recipes = Recipe.objects.all().filter(is_published=True).order_by('-id')
    
    page_obj, pagination_range = make_pagination(
        request=request,
        query_set=recipes,
        per_page=PER_PAGE,
        qty_pages=QTY_PAGES
    )
    
    # messages.error(request, 'ERRO')
    # messages.success(request, 'SUCESSO')
    # messages.info(request, 'INFO')
    # messages.debug(request, 'DEBUG')
    # messages.warning(request, 'WARN')
    
    return render(request, 'recipes/pages/home.html', context={
        'recipes': page_obj,
        'pagination_range': pagination_range
    })
    
def category(request, category_id):
    recipes = Recipe.objects.all().filter(
        category__id=category_id, 
        is_published=True
        ).order_by('-id')

    if not recipes:
        return HttpResponse(content="Not Found", status=404)
    
    page_obj, pagination_range = make_pagination(
        request=request,
        query_set=recipes,
        per_page=PER_PAGE,
        qty_pages=QTY_PAGES
    )
    
    return render(request, 'recipes/pages/home.html', context={
        'recipes': page_obj,
        'pagination_range': pagination_range,
        'title': recipes.first().category.name
        # 'recipes': [make_recipe(i) for i in range(10)]
    })

def recipe(request, id):
    recipe = Recipe.objects.all().filter(
        id=id, 
        is_published=True
        ).order_by('-id').first()
    
    if not recipe:
        return HttpResponse(content="Not Found", status=404)
    
    return render(request, 'recipes/pages/recipe-view.html', context={
        'recipe': recipe,
        'is_detail_page': True,
    })

def search(request):
    search_term = request.GET.get('q', '').strip()
    
    if not search_term:
        raise Http404()
    
    recipes = Recipe.objects.filter(
        Q(
            Q(title__icontains=search_term) |
            Q(description__icontains=search_term) |
            Q(category__name__icontains=search_term)
        ),
        is_published=True
    ).order_by('-id')
    
    page_obj, pagination_range = make_pagination(
        request=request,
        query_set=recipes,
        per_page=PER_PAGE,
        qty_pages=QTY_PAGES
    )
    
    return render(request, 'recipes/pages/search.html', context={
        'recipes': page_obj,
        'pagination_range': pagination_range,
        'page_title': f'Search for "{search_term}" |',
        'search_term': search_term,
        'additional_url_query': f'&q={search_term}'
    })

recipes/templates/recipes/partials/_footer.html
<footer class="main-footer">
    <div class="developer">
      <a href="#" target="_blank" rel="noreferrer noopener">By Gustavo C. Bellanda</a>
    </div>
  
    <div class="powered">
      <a href="https://www.djangoproject.com/" target="_blank" rel="noreferrer noopener">Powered by Django</a>
    </div>
  </footer>

recipes/templates/recipes/partials/_head.html
{% load static %}

<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/fontawesome.min.css"
    integrity="sha512-giQeaPns4lQTBMRpOOHsYnGw1tGVzbAIHUyHRgn7+6FmiEgGGjaG0T2LZJmAPMzRCl+Cug0ItQ2xDZpTmEc+CQ=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/brands.min.css"
    integrity="sha512-G/T7HQJXSeNV7mKMXeJKlYNJ0jrs8RsWzYG7rVACye+qrcUhEAYKYzaa+VFy6eFzM2+/JT1Q+eqBbZFSHmJQew=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/solid.min.css"
    integrity="sha512-6mc0R607di/biCutMUtU9K7NtNewiGQzrvWX4bWTeqmljZdJrwYvKJtnhgR+Ryvj+NRJ8+NnnCM/biGqMe/iRA=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@900&display=swap" rel="stylesheet">

<link rel="stylesheet" href="{% static 'recipes/css/style.css' %}">

recipes/templates/recipes/partials/_recipe.html
<div class="recipe recipe-list-item">
    <div class="recipe-cover">
        <a href="{% url 'recipes:recipe' recipe.id %}">
            <img src="{{ recipe.cover.url }}" alt="">
        </a>
        <div class="recipe-title-container">
            <h3 class="recipe-title">
                <a href="{% url 'recipes:recipe' recipe.id %}">
                    {{ recipe.title }}
                </a>
            </h3>
           
        </div>

        <div class="recipe-author">
            <span class="recipe-author-item">
                <i class="fas fa-user"></i>
                {% if recipe.author.first_name %}
                    {{ recipe.author.first_name }} {{ recipe.author.last_name }}
                {% else %}
                    {{ recipe.author.username }}
                {% endif %}
            </span>
            <span class="recipe-author-item">
                <i class="fas fa-calendar-alt"></i>
                {{ recipe.created_at|date:'d/m/Y à\s H:i:s' }}
            </span>
            <span class="recipe-author-item">
                <a href="{% url 'recipes:category' recipe.category.id %}">
                    <i class="fas fa-layer-group"></i>
                    <span>{{ recipe.category.name }}</span>
                </a>
            </span>
        </div>

        <div class="recipe-content">
            <p>{{ recipe.description }}</p>
        </div>

        <div class="recipe-meta-container">
            <div class="recipe-meta recipe-preparation">
                <h3 class="recipe-meta-title"><i class="fas fa-stopwatch"></i> Preparo</h3>
                <div class="recipe-meta-text">
                    {{ recipe.preparation_time }} {{ recipe.preparation_time_unit }}
                </div>
            </div>
            <div class="recipe-meta recipe-servings">
                <h3 class="recipe-meta-title"><i class="fas fa-pizza-slice"></i> Porções</h3>
                <div class="recipe-meta-text">
                    {{ recipe.servings }} {{ recipe.servings_unit }}
                </div>
            </div>
        </div>
        {% if is_detail_page is not True %}
        <footer class="recipe-footer">
            <a class="recipe-read-more button button-dark button-full-width" href="{% url 'recipes:recipe' 0 %}">
                <i class="fas fa-eye"></i>
                <span>ver mais...</span>
            </a>
        </footer>
        {% endif %}
        {% if is_detail_page is True %}
            <div class="preparation-steps">
                {% if recipe.preparation_steps_is_html is True %}
                    {{ recipe.preparation_steps|safe }}
                {% else %}
                    {{ recipe.preparation_steps|linebreaksbr }}
                {% endif %}
            </div>
        {% endif %}
    </div>
</div>