authors/urls.py
from django.urls import path

from authors import views

app_name = 'authors'

urlpatterns = [
    # * Register
    path("register/", views.register_view, name='register'),
    path("register/create/", views.register_create, name='register_create'),
    # * Login & Logout
    path("login/", views.login_view, name='login'),
    path("login/create/", views.login_create, name='login_create'),
    path("login/logout_view/", views.logout_view, name='logout_view'),
    # * Dashboard
    path("dashboard/", views.dashboard, name='dashboard'),
    path(
        "dashboard/recipe/",
        views.dashboard_recipe_view,
        name='dashboard_recipe_view'
    ),
    path(
        "dashboard/recipe/create/",
        views.dashboard_recipe_create,
        name='dashboard_recipe_create'
    ),
    path(
        "dashboard/recipe/<int:id>/edit/",
        # views.DashboardRecipe.as_view(),
        views.dashboard_recipe_edit,
        name='dashboard_recipe_edit'
    ),
    path(
        "dashboard/recipe/delete/",
        views.dashboard_recipe_delete,
        name='dashboard_recipe_delete'
    ),
]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('recipes.urls')),
    path("authors/", include('authors.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authors/models.py
from django.db import models

# Create your models here.

authors/forms/LoginForm.py
from django import forms


class LoginForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(attrs={
            'placeholder': 'Type Your Username',
            'class': 'form-control'
        })
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={
            'placeholder': 'Type Your Password',
            'class': 'form-control'
        })
    )

authors/forms/RecipeForm.py
from collections import defaultdict

from django import forms
from django.core.exceptions import ValidationError

from recipes.models import Recipe
from utils.django_forms import add_attr


class RecipeForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        self._my_errors = defaultdict(list)
        
        add_attr(self.fields.get('preparation_steps'), 'parentClassName', 'col-md-12')
        add_attr(self.fields.get('cover'), 'parentClassName', 'col-md-12')
     
        add_attr(self.fields.get('preparation_steps'), 'class', 'form-control')
        add_attr(self.fields.get('cover'), 'class', 'form-control')
    
    preparation_time_unit = forms.CharField(
        required=True,
        widget=forms.Select(
            attrs={
            'class': 'form-control'
            },
            choices=(
                ('Minutos', 'Minutos'),
                ('Horas', 'Horas'),
            )
        ),
        label="Preparation Time Unit",
    )
    
    servings_unit = forms.CharField(
        required=True,
        widget=forms.Select(
            # attrs={
            # 'class': 'form-control'
            # },
            choices=(
                ('Porções', 'Porções'),
                ('Pedaços', 'Pedaços'),
                ('Pessoas', 'Pessoas'),
            )
        ),
        label="Servings Unit",
    )
    
    class Meta:
        model=Recipe
        fields= ('title', 'description', 'preparation_time', 'preparation_time_unit', 'servings', 'servings_unit', 'category', 'preparation_steps', 'cover')
        
    def clean(self, *args, **kwargs):
        super_clean = super().clean(*args, **kwargs)
        
        cleaned_data = self.cleaned_data
        title = cleaned_data.get('title')
        description = cleaned_data.get('description')
        
        if len(title or '') < 5:
            self._my_errors['title'].append('Must have at least 5 chars')
            
        if title == description:
            self._my_errors['title'].append('Title and description cannot be equal')
            self._my_errors['description'].append('Title and description cannot be equal')
            
        if self._my_errors:
            raise ValidationError(self._my_errors)
        
        return super_clean

authors/views/dashboard.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.shortcuts import redirect, render
from django.urls import reverse

from authors.forms import RecipeForm
from recipes.models import Recipe


# * DASHBOARD
@login_required(login_url='authors:login', redirect_field_name='next')
def dashboard(request):
    recipes = Recipe.objects.filter(
        is_published=False,
        author=request.user
    )
    
    return render(request, 'authors/pages/dashboard.html', {
        'recipes': recipes
    })
    
@login_required(login_url='authors:login', redirect_field_name='next')
def dashboard_recipe_view(request):
    dashboard_recipe_new_form_data = request.session.get('dashboard_recipe_new_form_data', None)
    
    form = RecipeForm(dashboard_recipe_new_form_data)

    return render(request, 'authors/pages/dashboard_recipe_new.html', {
        'form': form,
        'form_action': reverse('authors:dashboard_recipe_create')
    })
    
@login_required(login_url='authors:login', redirect_field_name='next')
def dashboard_recipe_create(request):
    if not request.POST:
        raise(Http404())
    
    POST = request.POST
    
    request.session['dashboard_recipe_new_form_data'] = POST
    
    form = RecipeForm(
        request.POST or None,
        files=request.FILES or None
    )
    

    if form.is_valid():
        recipe = form.save(commit=False)
        
        recipe.author = request.user
        recipe.preparation_steps_is_html = False
        recipe.is_published = False
        
        recipe.save()
        
        messages.success(request, 'Your recipe has been successfully saved')
        
        del(request.session['dashboard_recipe_new_form_data'])
        
        return redirect(reverse('authors:dashboard'))
    
    return redirect('authors:dashboard_recipe_view')

@login_required(login_url='authors:login', redirect_field_name='next')
def dashboard_recipe_edit(request, id):
    recipe = Recipe.objects.filter(
        is_published=False,
        author=request.user,
        pk=id
    ).first()
    
    if not recipe:
        raise Http404()
    
    form = RecipeForm(
        request.POST or None,
        files=request.FILES or None,
        instance=recipe
    )
    
    if form.is_valid():
        recipe = form.save(commit=False)
        
        recipe.author = request.user
        recipe.preparation_steps_is_html = False
        recipe.is_published = False
        
        recipe.save()
        
        messages.success(request, 'Your recipe has been successfully saved')
        
        return redirect(reverse('authors:dashboard_recipe_edit', args=(id,)))
    
    return render(request, 'authors/pages/dashboard_recipe.html', {
        'recipe': recipe,
        'form': form
    })


@login_required(login_url='authors:login', redirect_field_name='next')
def dashboard_recipe_delete(request):
    if not request.POST:
        raise(Http404())
    
    POST = request.POST
    id = POST.get('id')
    
    recipe = Recipe.objects.filter(
        is_published=False,
        author=request.user,
        pk=id
    ).first()
    
    if not recipe:
        raise Http404()

    recipe.delete()
    messages.success(request, 'Delete Successfully!')
    return redirect(reverse('authors:dashboard'))

authors/views/dashboard_recipe.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.shortcuts import redirect, render
from django.urls import reverse
from django.views import View

from authors.forms import RecipeForm
from recipes.models import Recipe


class DashboardRecipe(View):
    def get_recipe(self, id):
        recipe = None
        
        if id:
            recipe = Recipe.objects.filter(
                is_published=False,
                author=self.request.user,
                pk=id
            ).first()
            
            if not recipe:
                raise Http404()
    
    def get(self, request, id):
        recipe = self.get_recipe(id)
        
        form = RecipeForm(instance=recipe)

        
        return render(request, 'authors/pages/dashboard_recipe.html', {
            'recipe': recipe,
            'form': form
        })
    def post(self, request, id):
        self.request

        recipe = Recipe.objects.filter(
            is_published=False,
            author=request.user,
            pk=id
        ).first()
        
        if not recipe:
            raise Http404()
        
        form = RecipeForm(
            request.POST or None,
            files=request.FILES or None,
            instance=recipe
        )
        
        if form.is_valid():
            recipe = form.save(commit=False)
            
            recipe.author = request.user
            recipe.preparation_steps_is_html = False
            recipe.is_published = False
            
            recipe.save()
            
            messages.success(request, 'Your recipe has been successfully saved')
            
            return redirect(reverse('authors:dashboard_recipe_edit', args=(id,)))
        
        return render(request, 'authors/pages/dashboard_recipe.html', {
            'recipe': recipe,
            'form': form
        })     

authors/views/login.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.shortcuts import redirect, render
from django.urls import reverse

from authors.forms import LoginForm


# * LOGIN
def login_view(request):
    login_form_data = request.session.get('login_form_data', None)
    
    form = LoginForm(login_form_data)

    return render(request, 'authors/pages/login_new.html', {
        'form': form,
        'form_action': reverse('authors:login_create')
    })
    
def login_create(request):
    if not request.POST:
        raise(Http404())
    
    POST = request.POST
    request.session['login_form_data'] = POST
    
    form = LoginForm(POST)
    login_url = reverse('authors:login')
    
    if form.is_valid():
        authenticated_user = authenticate(
            username=form.cleaned_data.get('username', ''),
            password=form.cleaned_data.get('password', ''),
        )
        
        if authenticated_user is not None:
            del(request.session['login_form_data'])
            
            messages.success(request, 'You are logged in.')
            login(request=request, user=authenticated_user)
            return redirect(reverse('authors:dashboard'))
        
        messages.error(request, 'Invalid credentials!')
        return redirect(login_url)
    
    messages.error(request, 'Error to validate form data!')
    return redirect(login_url)

# * LOGOUT
@login_required(login_url='authors:login', redirect_field_name='next')
def logout_view(request):
    logout(request)
    
    return redirect(reverse('authors:login'))

authors/views/register.py
from django.contrib import messages
from django.http import Http404
from django.shortcuts import redirect, render
from django.urls import reverse

from authors.forms import RegisterForm


# Create your views here.
# * REGISTER
def register_view(request):
    register_form_data = request.session.get('register_form_data', None)
    
    form = RegisterForm(register_form_data)
    
    return render(request, 'authors/pages/register_new.html', {
        'form': form,
        'form_action': reverse('authors:register_create')
    })
    
def register_create(request):
    if not request.POST:
        raise(Http404())
    
    POST = request.POST
    request.session['register_form_data'] = POST
    form = RegisterForm(POST)
    
    if form.is_valid():
        user = form.save(commit=False)
        user.set_password(user.password)
        user.save()
        
        messages.success(request, 'Your user is created, please log in.')
        
        del(request.session['register_form_data'])
        
        return redirect(reverse('authors:login'))

    return redirect('authors:register')

authors/templates/authors/pages/dashboard.html
{% extends 'global/base.html' %}
{% block title %}Dashboard | {% endblock title %}

{% block content %}
    <div class="main-content container">
        <div class="center">
            <h1>{{ time }}</h1>
            <h2>Dashboard ({{ user }})</h2>

            {% include 'global/partials/_messages.html' %}
            {% include 'authors/partials/_login_message.html' %}

        </div>

        <div class="authors-dashboard-container">
            <a href="{% url 'authors:dashboard_recipe_view' %}">Create new recipe</a>
            <h4>Your Recipes</h4>

            <ul>
                {% for recipe in recipes %}
                    <li>
                        <a href="{% url 'authors:dashboard_recipe_edit' recipe.id %}">{{ recipe.title }}</a>
                        <form
                        class="inline-form form-delete"
                        action="{% url 'authors:dashboard_recipe_delete' %}" 
                        method="POST"
                        >
                            {% csrf_token %}
                            <input type="hidden" name="id", value="{{ recipe.id }}">
                            <button class="plaintext-button" type="submit">❌</button>
                        </form>
                    </li>
                {% empty %}
                You do not have recipes, Please create one.
                {% endfor %}
            </ul>
        </div>
    </div>

{% endblock content %}

authors/templates/authors/pages/dashboard_recipe.html
{% extends 'global/base.html' %}

{% block title %}Dashboard Recipe | {% endblock title %}

{% block content %}
    <div class="main-content center container">
        <h2>Dashboard Recipe</h2>

        {% include 'authors/partials/_login_message.html' %}

        <div class="authors-dashboard-container">
            {% include 'global/partials/_form.html' %}
        </div>
        
    </div>

{% endblock content %}

authors/templates/authors/pages/dashboard_recipe_new.html
{% extends 'global/base.html' %}

{% block title %}Dashboard Create Recipe | {% endblock title %}

{% block content %}
    <div class="main-content center container">
        <h2>Dashboard Create Recipe</h2>

        {% include 'authors/partials/_login_message.html' %}

        <div class="authors-dashboard-container">
            {% include 'global/partials/_form.html' %}
        </div>
        
    </div>

{% endblock content %}

authors/templates/authors/pages/login_new.html
{% extends 'global/base.html' %}
{% block title %}Login | {% endblock title %}

{% block content %}
    <div class="main-content center container">
        <h2>Login</h2>
        {% include 'authors/partials/_login_message.html' %}
    </div>

    {% if not user.is_authenticated %}
        {% include 'global/partials/_form.html' %}
    {% endif %}

{% endblock content %}

authors/templates/authors/pages/register_new.html
{% extends 'global/base.html' %}
{% block title %}Register | {% endblock title %}

{% block content %}
    <div class="main-content center container">
        <h2>Register</h2>
    </div>

    {% include 'global/partials/_form.html' %}
{% endblock content %}